<a href="https://colab.research.google.com/github/p37102599-crypto/Data_Analysis/blob/Python_Fundamental/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is a Python library , was created in 2005 by Travis oliphant . Numpy is short for" Numerical Python" . 50x fastern than traditional pyhton lists.


In [ ]:
#importing numpy library
import  numpy as np
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


Different ways to create numpy array

In [ ]:
# to create an ndarray , we can pass a  list,tuple or
#other array like object

In [ ]:
#create 2Darray
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [ ]:
# to see the dimension
print(arr3.ndim)

2


In [ ]:
#create a 3d Array
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr4)
print(arr4.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
#numpy array indexing
arr5 = np.array([1,2,3,4,5])
print(arr5[2])

3


In [ ]:
print(arr5[0:3])

[1 2 3]


In [ ]:
print(arr5[0:3])
#using negative index
print(arr5[-1])
print(arr5[-2:-1])

[1 2 3]
5
[4]


In [ ]:
# get the third and fourth value and add them
print(arr5[2]+arr5[3])

7


In [ ]:
#Access the element on the first row , second column
arr6 =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr6)
print('2nd element on 1st row' , arr6[0,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row 2


In [ ]:
#Access the element on the 2nd row and 5th column
arr7 =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr6)
print('5th element on 2nd row' , arr7[1,4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd row 10


In [ ]:
#import as numpy as np
arr8 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr8)
print(arr8[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [ ]:
#print the last element from the 2nd dim
#import numpy as np
arr9 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from the 2nd dim : ' ,arr9[1,-1])

Last element from the 2nd dim :  10


In [ ]:
#Slice elemnets from indx 1 to idx 5 from the following array:
#import numpy as np
arr10= np.array([10,20,30,40,50,60,75])
print(arr10[1:5])
print(arr10[4:])
print(arr10[:4])

[20 30 40 50]
[50 60 75]
[10 20 30 40]


In [ ]:
# slice from the idx 3 from the end to idx 1 from the end
arr11 = np.array([1,2,3,4,5,6,7])
print(arr11[-3:-1])
# use step value
print(arr11[1:5:2])
#return every other element from the entire array:
print(arr11[::2])

[5 6]
[2 4]
[1 3 5 7]


In [ ]:
#slicing the 2D array
#from the 2nd element ,slice elements from idx 1 to idx 4
arr12 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr12[1,1:4])
print(arr12[0:2,1:4])
print(arr12[0:2,2])

[7 8 9]
[[2 3 4]
 [7 8 9]]
[3 8]


# Datatypes in numpy
#i - integer
#b - boolean
#u - unsigned integer
#f - float
#c - complex float
#m - timedelta
#M - datetime
#0 - object
#s- string



In [ ]:
#creating arrays with a defined datatype with integer
arr = np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
#creating arrays with a defined datatype with string
arr = np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# Change data type from float to integer
arr11 = np.array([2.1,3.1,4.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


##v numpy array copy v/s view
## the main differnce between a copy and a view of an array is that the copy is a new array,and the view is just a view of the original array

In [ ]:
#make a copy ,change the original array and display both arrays
#import numpy as np
arr  = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5])
x= arr.view()
print(arr)
arr[0]=42
print(arr)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#numpy array shape
arr =np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
#reshaping
arr =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#flattening the array
arr =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
newarr = arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#numpy array iterating
arr = np.array([1,2,3])
for x in arr:
  print(x)

1
2
3
