<a href="https://colab.research.google.com/github/p37102599-crypto/Data_Analysis/blob/Practise_questions/practisequestions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print("Shape:", arr.shape)
print("Size:",arr.size)
print("Data type:",arr.dtype)

[10 20 30 40 50]
Shape: (5,)
Size: 5
Data type: int64


In [25]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [27]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [28]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
even  = np.arange(10,51,2)
print(even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [30]:
arr = np.linspace(0, 1, 10)

print(arr)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Array arithmetic


In [31]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])
print(a + b)
print(a - b)
print(a * b)
print(a / b)


[12 24 35 48]
[ 8 16 25 32]
[ 20  80 150 320]
[5. 5. 6. 5.]


In [32]:
arr = np.array([1, 2, 3, 4, 5])
print(arr ** 2)
print(arr ** 3)


[ 1  4  9 16 25]
[  1   8  27  64 125]


In [33]:
arr = np.array([100, 200, 300, 400])
arr = arr * 1.15
print(arr)


[115. 230. 345. 460.]


In [34]:
a = np.array([10, 25, 30, 45])
b = np.array([15, 20, 35, 40])
print(np.maximum(a, b))
print(np.minimum(a, b))


[15 25 35 45]
[10 20 30 40]


Indexing and slicing

In [35]:
import numpy as np
arr = np.arange(21)
print("Array:", arr)
print("First five:", arr[:5])
print("Last five:", arr[-5:])
print("Index 5 to 15:", arr[5:16])
print("Every second:", arr[::2])


Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second: [ 0  2  4  6  8 10 12 14 16 18 20]


In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[:5] = 100
print(arr)


[100 100 100 100 100   6   7   8   9  10]


In [37]:
arr = np.array([10, 20, 30, 40, 50])
view = arr[1:4]
view[0] = 100
print("Original array:", arr)
print("View:", view)


Original array: [ 10 100  30  40  50]
View: [100  30  40]


In [38]:
arr = np.array([10, 20, 30, 40, 50])
reverse = arr[::-1]
print(reverse)


[50 40 30 20 10]


2D array indexing and slicing

In [39]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]])
print("Second row:", arr[1])
print("Third column:", arr[:, 2])
print("Element 50:", arr[1, 1])


Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


In [40]:
sub = arr[0:2, 1:3]
print(sub)

[[20 30]
 [50 60]]


In [41]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Reshaping and Transpose

In [42]:
import numpy as np
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
arr = np.arange(1, 11)
matrix = arr.reshape(2, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [44]:
arr = np.arange(1, 13).reshape(3, 4)
print("Original:")
print(arr)
transpose = arr.T
print("Transpose:")
print(transpose)

Original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [45]:
arr = np.arange(1, 25).reshape(2, 3, 4)
print("Original shape:", arr.shape)
print(arr)

Original shape: (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
